@extends('home') 
@section('homecontent')
<style>
th { font-size: 12px; }
td { font-size: 11px; }
th, td { white-space: nowrap; }
div.container {
	min-width: 980px;
	margin: 0 auto;
}
div.ColVis {
        float: left;
    }
</style>

<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-md-11">
            <h3 class="page-header">
                Reporte BackOrder
                <small>Producción</small>
            </h3>

            <!-- <h5>Fecha & hora: {{date('d-m-Y h:i a', strtotime("now"))}}</h5> -->
        </div>
    </div>   
    <br>
    <!-- /.row -->
    <div class="row">
        <div class="container">
            <table  id="tbackorder" class="display">
                <thead >
                    <tr>
                        <th>OP</th>
                        <th>Pedido</th>
                        <th>F.pedido</th>
                        <th>OC</th>
                        <th>D_proc</th>
                        <th>No_serie</th>
                        <th>Cliente</th>
                        <th>Modelo</th>
                        <th>Acabado</th>
                        <th>Descripción</th>
                        <th>Cant</th>
                        <th>%</th>
                        <th>Total %</th>
                        <th>Funda</th>
                        <th>Dias CT</th>
                        <th>Prg. Piel</th>
                        <th>Secue</th>
                        <th>Sec OT</th>
                        <th>Sem-C</th>
                        <th>F.Compras</th>
                        <th>F.Ventas</th>
                        <th>Sem-P</th>
                        <th>F.Produc.</th>
                        <th>Prioridad</th>
                        <th>Desv</th>
                        <th>Notas</th>
                        <th>Especiales</th>
                        <th>Nom Modelo</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

</div>
<!-- /.container -->
@endsection
 
@section('homescript')

document.onkeyup = function(e) {
   if (e.shiftKey && e.which == 112) {
    window.open("ayudas_pdf/AyM00_00.pdf","_blank");
  } 

$('#tbackorder thead tr').clone(true).appendTo( '#tbackorder thead' );

$('#tbackorder thead tr:eq(1) th').each( function (i) {
    var title = $(this).text();
    $(this).html( '<input style="color: black;"  type="text" placeholder="Filtro '+title+'" />' );
   
    $( 'input', this ).on( 'keyup change', function () {       
            
            if ( table.column(i).search() !== this.value ) {
                table
                    .column(i)
                    .search(this.value, true, false)
                    
                    .draw();
            } 
                
    } );
} );

var table = $('#tbackorder').DataTable({
    dom: 'Bfrtip',
    buttons: [
        { // default PDF and customized PDF
            extend: 'pdfHtml5',
            filename: 'border',
            title: 'Random Persons', // report header/title
            orientation: 'landscape',
            pageSize: 'A4',
            exportOptions: {
                       columns: ':visible',                
                   }, 
           download: 'open',
           customize: function ( doc ) {
                       // Splice the image in after the header, but before the table
                       doc.content.splice( 1, 0, {
                           margin: [ 0, 0, 0, 12 ],
                           alignment: 'center',                          
                       } );
                       // Data URL generated by http://dataurl.net/#dataurlmaker
                   }
        },
        'copy', 'excel',  {
            text: 'Pdf',
            action: function ( e, dt, node, config ) {
                window.open('hola','_blank');
            },           
        },
        {
            text: 'Columnas',
            extend: 'colvis',
            postfixButtons: [                                  
                {
                    text: 'Restaurar columnas',
                    extend: 'colvisRestore',     
                }             
                ]
        },
        {
            text: 'Imprimir',
            extend: 'print',
            title: 'Reporte de Back Order',
            exportOptions: {
                columns: ':visible',                
            }
        },
       
    ],
   
    orderCellsTop: true,    
    scrollY:        "300px",
    "pageLength": 50,
    scrollX:        true,
    scrollCollapse: true,
    paging:         true,
   
    processing: true,
    
    deferRender:    true,
    ajax: {
        url: '{!! route('datatables.showbackorder') !!}',
        data: function () {
                         
                        }              
    },
    columns: [        
        // { data: 'action', name: 'action', orderable: false, searchable: false}

        { data: 'OP', name:  'OP', orderable: true, searchable: true},
        { data: 'Pedido', name: 'Pedido'},
        { data: 'FechaPedido', name:  'FechaPedido'},
        { data: 'OC', name: 'OC'},
        { data: 'D_PROC', name: 'D_PROC'},
        { data: 'NO_SERIE', name: 'NO_SERIE'},
        { data: 'CLIENTE', name:  'CLIENTE'},
        { data: 'codigo1', name: 'codigo1'},
        { data: 'codigo3', name:  'codigo3'},
        { data: 'Descripcion', name:  'Descripcion'},
        { data: 'Cant', name:  'Cantidad'},
        { data: 'VSind', name:  'VSind' },
        { data: 'VS', name:  'VS'},
        { data: 'Funda', name:  'Funda'},
        { data: 'DEstacion', name:  'DEstacion' },
        { data: 'U_Grupo', name: 'U_Grupo' },
        { data: 'Secue', name:  'Secue'},
        { data: 'SecOT', name:  'SecOT' },
        { data: 'SEMANA2', name:  'SEMANA2'},
        { data: 'fentrega', name:  'fentrega'},
        { data: 'fechaentregapedido', name:  'fechaentregapedido'},
        { data: 'SEMANA3', name:  'SEMANA3'},
        { data: 'u_fproduccion', name:  'u_fproduccion'},
        { data: 'Prioridad', name:  'Prioridad'},
        { data: 'Desv', name:  'Desv'},
        { data: 'Comments', name:  'Comments'},
        { data: 'U_Especial', name:  'U_Especial'},
        { data: 'Modelo', name: 'Modelo'}
    ],
    "language": {
        "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
    },
    columnDefs: [
        { width: 80, targets: 2 },
        { width: 80, targets: 3 },
        { width: 100, targets: 6 },
        { width: 150, targets: 9 },
        { width: 80, targets: 13 },
        { width: 150, targets: 25 },
        { width: 150, targets: 27 },
    ],
    //revision
    fixedColumns:   {
        leftColumns: 1,
        rightColumns: 1
    }
});
@endsection

<script>
</script>



